import React, { createContext, useContext, useEffect, useState } from "react";

export type CashierLanguage = "vi" | "en";

interface CashierLocaleContextValue {
  language: CashierLanguage;
  setLanguage: (language: CashierLanguage) => void;
  isEnglish: boolean;
}

const CashierLocaleContext = createContext<CashierLocaleContextValue | null>(null);

const VI_TO_EN: Record<string, string> = {
  "Bàn & Khu vực": "Tables & Areas",
  "Thanh toán": "Checkout",
  "Lịch sử & Hoàn tiền": "History & Refunds",
  "Doanh thu & Audit": "Revenue & Audit",
  "Cài đặt": "Settings",
  "Hỗ trợ": "Support",
  "Đơn hàng mới": "New Order",
  "Checkout Express": "Checkout Express",
  "Table Status": "Table Status",
  "Manage dining areas and live orders.": "Manage dining areas and live orders.",
  "Bàn Chờ TT": "Pending Payment",
  "Lịch Sử Giao Dịch": "Transaction History",
  "Giao dịch hôm nay": "Today's Transactions",
  "Mã Đơn": "Order ID",
  "Thời Gian": "Time",
  "Bàn": "Table",
  "Số Tiền": "Amount",
  "Thanh Toán": "Payment",
  "Trạng Thái": "Status",
  "Xuất": "Export",
  "Lọc": "Filter",
  "Tách hóa đơn": "Split Bill",
  "Gộp hóa đơn": "Merge Bill",
  "Báo cáo cuối ngày": "End of Day Report",
  "Hoàn tiền": "Refund",
  "Hoàn tiền thành công": "Refund successful",
  "Lý do hoàn tiền": "Refund reason",
  "Loại hoàn tiền": "Refund type",
  "Toàn phần": "Full refund",
  "Một phần theo món": "Partial by item",
  "Chọn món cần hoàn tiền": "Select items to refund",
  "Đóng / Hủy": "Close / Cancel",
  "Xác nhận hoàn tiền ngay": "Confirm refund now",
  "Manager Approval": "Manager Approval",
  "Order Items": "Order Items",
  "Order Total": "Order Total",
  "View Order": "View Order",
  "Refund / Cancel": "Refund / Cancel",
  "Mark Clean": "Mark Clean",
  "Seat Guests": "Seat Guests",
  "Empty": "Empty",
  "Dirty": "Dirty",
  "Guests": "Guests",
  "Dining time": "Dining time",
  "Không tìm thấy giao dịch": "No transactions found",
  "Không tìm thấy bàn": "No tables found",
  "Clear filters": "Clear filters",
  "Tìm kiếm đơn hàng...": "Search orders...",
  "Search tables or orders...": "Search tables or orders...",
  "Tìm kiếm bàn...": "Search tables...",
  "Áp dụng": "Apply",
  "Tổng cộng": "Total",
  "Tạm tính": "Subtotal",
  "Tổng tiền cần thu": "Amount due",
  "Thanh toán ngay": "Pay now",
  "Đang phục vụ": "Serving",
  "Đã chọn": "Selected",
  "Dòng món": "Item lines",
  "Danh sách bàn đang mở": "Open tables",
  "Chọn ít nhất 2 bàn để thực hiện gộp hóa đơn": "Select at least 2 tables to merge bills",
  "Chưa chọn bàn": "No table selected",
  "Hóa đơn gộp dự kiến": "Merged bill preview",
  "TỔNG CỘNG": "TOTAL",
  "Số tiền khách đưa": "Cash received",
  "Tiền thừa": "Change",
  "Phương thức thanh toán": "Payment method",
  "Đã hoàn tất": "Completed",
  "Đang xử lý": "Processing",
  "Hủy": "Cancel",
  "Lưu": "Save",
  "Đặt lại": "Reset",
  "Lưu cấu hình": "Save configuration",
  "Chọn số người để chia hóa đơn.": "Choose the number of people to split the bill.",
  "Số tiền": "Amount",
  "Xác nhận thanh toán": "Confirm payment",
  "Hệ thống đang hoạt động": "System operational",
  "Terminal 01": "Terminal 01",
  "Báo cáo được tạo từ ROMS POS.": "Report generated by ROMS POS.",
  "Tạo đơn hàng mới cho khách.": "Create a new order for the customer.",
  "Dine-in": "Dine-in",
  "Mang đi": "Takeaway",
  "khách": "guests",
  "phút trước": "minutes ago",
  "Vừa xong": "Just now",
};

const EN_TO_VI = Object.fromEntries(
  Object.entries(VI_TO_EN).map(([vietnamese, english]) => [english, vietnamese]),
);

function translateCashierDom(language: CashierLanguage) {
  const dictionary = language === "en" ? VI_TO_EN : EN_TO_VI;
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const textNodes: Text[] = [];

  while (walker.nextNode()) textNodes.push(walker.currentNode as Text);

  textNodes.forEach((node) => {
    const value = node.nodeValue ?? "";
    const trimmed = value.trim();
    const translated = dictionary[trimmed];

    if (translated) {
      node.nodeValue = value.replace(trimmed, translated);
    }
  });

  document.querySelectorAll<HTMLElement>("[placeholder], [title], [aria-label]").forEach((element) => {
    ["placeholder", "title", "aria-label"].forEach((attribute) => {
      const value = element.getAttribute(attribute);
      if (value && dictionary[value]) element.setAttribute(attribute, dictionary[value]);
    });
  });
}

function getInitialLanguage(): CashierLanguage {
  if (typeof window === "undefined") return "vi";

  return window.localStorage.getItem("cashier-language") === "en" ? "en" : "vi";
}

export function CashierLocaleProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<CashierLanguage>(getInitialLanguage);

  useEffect(() => {
    window.localStorage.setItem("cashier-language", language);
    if (typeof document === "undefined") return;

    const applyTranslations = () => translateCashierDom(language);
    applyTranslations();
    const observer = new MutationObserver(applyTranslations);
    observer.observe(document.body, { childList: true, subtree: true });

    return () => observer.disconnect();
  }, [language]);

  return (
    <CashierLocaleContext.Provider
      value={{ language, setLanguage, isEnglish: language === "en" }}
    >
      {children}
    </CashierLocaleContext.Provider>
  );
}

export function useCashierLocale() {
  const context = useContext(CashierLocaleContext);

  if (!context) {
    throw new Error("useCashierLocale must be used inside CashierLocaleProvider");
  }

  return context;
}
